-- Supabase Database Schema for Lead-Shield

-- 1. Clients Table
CREATE TABLE clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id TEXT UNIQUE NOT NULL,
  business_name TEXT NOT NULL,
  contact_email TEXT NOT NULL,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  has_seo BOOLEAN DEFAULT FALSE,
  has_google_ads BOOLEAN DEFAULT FALSE,
  has_fb_ads BOOLEAN DEFAULT FALSE,
  has_gmb BOOLEAN DEFAULT FALSE,
  historical_spam_count INT DEFAULT 0
);

-- 2. Profiles (Links to Supabase Auth Users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'client',
  client_id TEXT REFERENCES clients(client_id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. N8n Configs
CREATE TABLE n8n_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id TEXT UNIQUE REFERENCES clients(client_id) ON DELETE CASCADE,
  gemini_prompt TEXT NOT NULL,
  gemini_models JSONB NOT NULL,
  openai_enabled BOOLEAN DEFAULT FALSE,
  openai_prompt TEXT,
  genuine_recipient_email TEXT,
  spam_recipient_email TEXT,
  webhook_url TEXT
);

-- 4. GMB Metrics
CREATE TABLE gmb_metrics (
  id TEXT PRIMARY KEY,
  client_id TEXT REFERENCES clients(client_id) ON DELETE CASCADE,
  year INT NOT NULL,
  month TEXT NOT NULL,
  call_clicks INT DEFAULT 0
);

-- 5. Leads
CREATE TABLE leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id TEXT REFERENCES clients(client_id) ON DELETE CASCADE,
  form_data JSONB NOT NULL,
  status TEXT NOT NULL,
  ai_reason TEXT,
  channel TEXT DEFAULT 'website',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Setup Row Level Security (RLS) policies (Optional but recommended)
-- For now, enabling open access for MVP migration. You should restrict this before production.
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE n8n_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE gmb_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write for clients" ON clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write for profiles" ON profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write for n8n_configs" ON n8n_configs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write for gmb_metrics" ON gmb_metrics FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write for leads" ON leads FOR ALL USING (true) WITH CHECK (true);

-- 6. Postgres Trigger for Preserving Spam Counts
-- When a spam lead is deleted (manually or by auto-cleanup), it increments the historical counter.
CREATE OR REPLACE FUNCTION preserve_spam_count()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.status = 'SPAM' THEN
    UPDATE clients SET historical_spam_count = historical_spam_count + 1 WHERE client_id = OLD.client_id;
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_preserve_spam_count ON leads;
CREATE TRIGGER trigger_preserve_spam_count
BEFORE DELETE ON leads
FOR EACH ROW EXECUTE FUNCTION preserve_spam_count();

-- 7. Postgres Function for 30-Day Auto Cleanup
-- This function can be called via API or pg_cron to safely shred 30-day old spam leads
CREATE OR REPLACE FUNCTION cleanup_old_spam()
RETURNS void AS $$
BEGIN
  DELETE FROM leads 
  WHERE status = 'SPAM' 
  AND created_at < NOW() - INTERVAL '30 days';
END;
$$ LANGUAGE plpgsql;
